/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_synthuse_MsgHook */

#ifndef _Included_org_synthuse_MsgHook
#define _Included_org_synthuse_MsgHook
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_synthuse_MsgHook
 * Method:    createMsgHookWindow
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_synthuse_MsgHook_createMsgHookWindow
  (JNIEnv *, jobject);

/*
 * Class:     org_synthuse_MsgHook
 * Method:    setMsgHookWindowTargetHwnd
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_synthuse_MsgHook_setMsgHookWindowTargetHwnd
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_synthuse_MsgHook
 * Method:    setMsgHookWindowTargetClass
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_synthuse_MsgHook_setMsgHookWindowTargetClass
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_synthuse_MsgHook
 * Method:    setMessageHook
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_synthuse_MsgHook_setMessageHook
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_synthuse_MsgHook
 * Method:    removeMessageHook
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_synthuse_MsgHook_removeMessageHook
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
