/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_synthuse_MsgHook */

#ifndef _Included_org_synthuse_MsgHook
#define _Included_org_synthuse_MsgHook
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_synthuse_MsgHook
 * Method:    setMessageHook
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_synthuse_MsgHook_setMessageHook
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_synthuse_MsgHook
 * Method:    removeMessageHook
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_synthuse_MsgHook_removeMessageHook
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
