/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_synthuse_WpfBridge */

#ifndef _Included_org_synthuse_WpfBridge
#define _Included_org_synthuse_WpfBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_synthuse_WpfBridge
 * Method:    setFrameworkId
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_synthuse_WpfBridge_setFrameworkId
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_synthuse_WpfBridge
 * Method:    setTouchableOnly
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_synthuse_WpfBridge_setTouchableOnly
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_synthuse_WpfBridge
 * Method:    countDescendantWindows
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_synthuse_WpfBridge_countDescendantWindows__
  (JNIEnv *, jobject);

/*
 * Class:     org_synthuse_WpfBridge
 * Method:    countDescendantWindows
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_synthuse_WpfBridge_countDescendantWindows__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_synthuse_WpfBridge
 * Method:    countChildrenWindows
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_synthuse_WpfBridge_countChildrenWindows__
  (JNIEnv *, jobject);

/*
 * Class:     org_synthuse_WpfBridge
 * Method:    countChildrenWindows
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_synthuse_WpfBridge_countChildrenWindows__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_synthuse_WpfBridge
 * Method:    enumChildrenWindowIds
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_synthuse_WpfBridge_enumChildrenWindowIds
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_synthuse_WpfBridge
 * Method:    enumDescendantWindowIds
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_synthuse_WpfBridge_enumDescendantWindowIds__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_synthuse_WpfBridge
 * Method:    enumDescendantWindowIds
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_synthuse_WpfBridge_enumDescendantWindowIds__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_synthuse_WpfBridge
 * Method:    enumDescendantWindowInfo
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_synthuse_WpfBridge_enumDescendantWindowInfo
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_synthuse_WpfBridge
 * Method:    getRuntimeIdFromHandle
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_synthuse_WpfBridge_getRuntimeIdFromHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_synthuse_WpfBridge
 * Method:    getRuntimeIdFromPoint
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_synthuse_WpfBridge_getRuntimeIdFromPoint
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_synthuse_WpfBridge
 * Method:    getParentRuntimeId
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_synthuse_WpfBridge_getParentRuntimeId
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_synthuse_WpfBridge
 * Method:    getProperty
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_synthuse_WpfBridge_getProperty
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_synthuse_WpfBridge
 * Method:    getProperties
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_synthuse_WpfBridge_getProperties
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_synthuse_WpfBridge
 * Method:    getPropertiesAndValues
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_synthuse_WpfBridge_getPropertiesAndValues
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
