/*
 * Copyright 2014, Synthuse.org
 * Released under the Apache Version 2.0 License.
 *
 * last modified by ejakubowski7@gmail.com
*/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_synthuse_WpfBridge */

#ifndef _Included_org_synthuse_WpfBridge
#define _Included_org_synthuse_WpfBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_synthuse_WpfBridge
 * Method:    SetFrameworkId
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_synthuse_WpfBridge_SetFrameworkId
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_synthuse_WpfBridge
 * Method:    CountDescendantWindows
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_synthuse_WpfBridge_CountDescendantWindows__
  (JNIEnv *, jobject);

/*
 * Class:     org_synthuse_WpfBridge
 * Method:    CountDescendantWindows
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_synthuse_WpfBridge_CountDescendantWindows__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_synthuse_WpfBridge
 * Method:    CountChildrenWindows
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_synthuse_WpfBridge_CountChildrenWindows__
  (JNIEnv *, jobject);

/*
 * Class:     org_synthuse_WpfBridge
 * Method:    CountChildrenWindows
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_synthuse_WpfBridge_CountChildrenWindows__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_synthuse_WpfBridge
 * Method:    EnumChildrenWindowIds
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_synthuse_WpfBridge_EnumChildrenWindowIds
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_synthuse_WpfBridge
 * Method:    EnumDescendantWindowIds
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_synthuse_WpfBridge_EnumDescendantWindowIds__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_synthuse_WpfBridge
 * Method:    EnumDescendantWindowIds
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_synthuse_WpfBridge_EnumDescendantWindowIds__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_synthuse_WpfBridge
 * Method:    EnumDescendantWindowIdsFromHandle
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_synthuse_WpfBridge_EnumDescendantWindowIdsFromHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_synthuse_WpfBridge
 * Method:    GetProperty
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_synthuse_WpfBridge_GetProperty
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_synthuse_WpfBridge
 * Method:    GetProperties
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_synthuse_WpfBridge_GetProperties
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_synthuse_WpfBridge
 * Method:    GetPropertiesAndValues
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_synthuse_WpfBridge_GetPropertiesAndValues
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
