/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_synthuse_UiaBridge */

#ifndef _Included_org_synthuse_UiaBridge
#define _Included_org_synthuse_UiaBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_synthuse_UiaBridge
 * Method:    initialize
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_synthuse_UiaBridge_initialize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_synthuse_UiaBridge
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_synthuse_UiaBridge_shutdown
  (JNIEnv *, jobject);

/*
 * Class:     org_synthuse_UiaBridge
 * Method:    useCachedRequests
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_synthuse_UiaBridge_useCachedRequests
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_synthuse_UiaBridge
 * Method:    addEnumFilter
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_synthuse_UiaBridge_addEnumFilter
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_synthuse_UiaBridge
 * Method:    clearEnumFilters
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_synthuse_UiaBridge_clearEnumFilters
  (JNIEnv *, jobject);

/*
 * Class:     org_synthuse_UiaBridge
 * Method:    enumWindowInfo
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_synthuse_UiaBridge_enumWindowInfo__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_synthuse_UiaBridge
 * Method:    enumWindowInfo
 * Signature: (ILjava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_synthuse_UiaBridge_enumWindowInfo__ILjava_lang_String_2
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_synthuse_UiaBridge
 * Method:    getWindowInfo
 * Signature: (IILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_synthuse_UiaBridge_getWindowInfo__IILjava_lang_String_2
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     org_synthuse_UiaBridge
 * Method:    getWindowInfo
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_synthuse_UiaBridge_getWindowInfo__ILjava_lang_String_2
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_synthuse_UiaBridge
 * Method:    getWindowInfo
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_synthuse_UiaBridge_getWindowInfo__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
